# Etapa de construcción
FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install @mui/material @mui/icons-material uuid
COPY . .
RUN npm run build

# Etapa de producción
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Si tienes archivos personalizados de configuración de Nginx, descomenta la siguiente línea:
COPY nginx/conf.d /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]