apiVersion: batch/v1
kind: Job
metadata:
  name: discount-people-service-db-populate
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:latest
        command: ["sh", "-c", "mysql -h discount-people-service-db-service -uroot -proot < /scripts/discount-people-service-db.mysql.sql"]
        volumeMounts:
        - name: sql-script
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: sql-script
        configMap:
          name: discount-people-service-db-sql
