apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-frequent-service-deployment
  labels:
    app: discount-frequent-service-deployment
spec:
  selector:
    matchLabels:
      app: discount-frequent-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: discount-frequent-service-deployment
    spec:
      containers:
        - name: discount-frequent-service
          image: duvanvergara/discount-frequent-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_DISCOUNT_FREQUENT
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_DISCOUNT_FREQUENT
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_DISCOUNT_FREQUENT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-user-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: discount-frequent-service-service
  labels:
    app: discount-frequent-service-service
spec:
  selector:
    app: discount-frequent-service-deployment
  ports:
    - nodePort: 30003
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
