apiVersion: batch/v1
kind: Job
metadata:
  name: karting-db-populate-load-job
  namespace: default
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: mysql-populate
        image: mysql:8.0
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "karting_db"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: password
        command:
        - /bin/bash
        - -c
        - |
          echo "Esperando MySQL..."
          until mysql -h$MYSQL_HOST -P$MYSQL_PORT -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1" > /dev/null 2>&1; do
            echo "MySQL no disponible aún..."
            sleep 5
          done
          echo "MySQL disponible, ejecutando población..."
          mysql -h$MYSQL_HOST -P$MYSQL_PORT -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < /sql/populate.sql
          echo "Población completada para escenario: Load"
        volumeMounts:
        - name: sql-volume
          mountPath: /sql
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: sql-volume
        configMap:
          name: karting-db-populate-load-config
