apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m1-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1-db-deployment
spec:
  selector:
    matchLabels:
      app: m1-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: m1-db
        tier: database
    spec:
      containers:
        - name: m1-db
          image: mysql:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-credentials
                  key: password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: m1-db-data
      volumes:
        - name: m1-db-data
          persistentVolumeClaim:
            claimName: m1-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: m1-db-service
  labels:
    app: m1-db-service
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: m1-db
    tier: database
  type: ClusterIP