apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
  labels:
        app: mysql-config-map
data:
  # Configuración para M1
  DB_HOST_M1: "m1-db-service"
  DB_PORT_M1: "3306"
  DB_DBNAME_M1: "tartifasbd"
  # Configuración para M2
  DB_HOST_M2: "m2-db-service"
  DB_PORT_M2: "3306"
  DB_DBNAME_M2: "desctpersona"
  # Configuración para M3
  DB_HOST_M3: "m3-db-service"
  DB_PORT_M3: "3306"
  DB_DBNAME_M3: "desctpersonafrect"
  # Configuración para M4
  DB_HOST_M4: "m4-db-service"
  DB_PORT_M4: "3306"
  DB_DBNAME_M4: "tartiffspecialbd"
  # Configuración para M5
  DB_HOST_M5: "m5-db-service"
  DB_PORT_M5: "3306"
  DB_DBNAME_M5: "reserve"