apiVersion: apps/v1
kind: Deployment
metadata:
  name: rack-service-deployment
  labels:
    app: rack-service-deployment
spec:
  selector:
    matchLabels:
      app: rack-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: rack-service-deployment
    spec:
      containers:
        - name: rack-service
          image: duvanvergara/rack-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: rack-service-service
  labels:
    app: rack-service-service
spec:
  selector:
    app: rack-service-deployment
  ports:
    - nodePort: 30006
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
