apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-service-deployment
  labels:
    app: reports-service-deployment
spec:
  selector:
    matchLabels:
      app: reports-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: reports-service-deployment
    spec:
      containers:
        - name: reports-service
          image: duvanvergara/reports-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: reports-service-service
  labels:
    app: reports-service-service
spec:
  selector:
    app: reports-service-deployment
  ports:
    - nodePort: 30007
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
