apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-rates-service-deployment
  labels:
    app: special-rates-service-deployment
spec:
  selector:
    matchLabels:
      app: special-rates-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: special-rates-service-deployment
    spec:
      containers:
        - name: special-rates-service
          image: duvanvergara/special-rates-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_M4
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_M4
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_M4
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-user-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user-credentials
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: special-rates-service-service
  labels:
    app: special-rates-service-service
spec:
  selector:
    app: special-rates-service-deployment
  ports:
    - nodePort: 30004
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
